image:
  name: node:12

cache:
  paths:
    - node_modules/

before_script:
  - yarn install
  - node --version

pages:
  stage: deploy
  script:
    # This magical incantation will inject a build version just before </body>"
    - sed -i "s|</body>|<small>Built on GitLab branch <code>$CI_COMMIT_REF_NAME</code> commit <code>$CI_COMMIT_SHORT_SHA</code> $(date)</small></body>|g" public/index.html
    - npm run build   # Do a production build to build/ folder
    - rm -rf public   # React public/ shouldn't conflict with GitLab public/
    - mv build public # Move to the directory GitLab pages expects
    artifacts:
      paths:
        - public